site_name: SoftFIRE Software Documentation
pages:
        - SoftFIRE:
                - Introduction: 'index.md'
                - Softfire Middleware: 'softfire-middleware.md'
        - Wiki:
                - Getting Started: 'getting-started.md'
                - Experiment Manager: 'experiment-manager.md'
                - Define your experiment: 'experiment-definition.md'
                - NFV Manager: 'nfv-manager.md'
                - SDN Manager:
                  - General: 'sdn-manager.md'
                  - OpenSDNCore:
                    - Introduction: 'opensdncore.md'
                    - Controller: 'osdnc-controller.md'
                    - API Documentation: 'opensdncore-nb-api.md'
                    - OpenStack Integration: 'osdnc-openstack.md'
                  - OpenDayLight: 'opendaylight.md'
                - Physical Device Manager: 'pd-manager.md'
                - Security Manager: 'security-manager.md'
                  - Firewall: 'firewall.md'
                - Monitoring Manager: 'monitoring-manager.md'


        - Dev:
                - Write a sub manager: 'sub-manager.md'
                - SDN Manager developers: 'sdn-manager-dev.md'
        - Extras:
                - OpenVPN Manual configuration: 'openvpnconfig.md'

theme_dir: material
extra:
  palette:
    primary: 'deep orange'
    accent: 'orange'
  feature:
    tabs: false
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  social:
    - type: 'github'
      link: 'https://github.com/SoftFIRE-eu'

repo_url: https://github.com/SoftFIRE-eu/experiment-manager
repo_name: SoftFIRE Experiment Manager
site_favicon: favicon.ico
markdown_extensions:
          - admonition
          - codehilite
          - footnotes
          - toc(permalink=true)
          - pymdownx.arithmatex
          - pymdownx.betterem(smart_enable=all)
          - pymdownx.caret
          - pymdownx.critic
          - pymdownx.emoji:
                    emoji_generator: !!python/name:pymdownx.emoji.to_svg
          - pymdownx.inlinehilite
          - pymdownx.magiclink
          - pymdownx.mark
          - pymdownx.smartsymbols
          - pymdownx.superfences
          - pymdownx.tasklist(custom_checkbox=true)
          - pymdownx.tilde

copyright: Copyright (c) 2016-2017 SoftFIRE (http://softfire.eu)
